//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int GlobalBatchID { get; set; }
        public int BankID { get; set; }
        public int LockboxID { get; set; }
        public Nullable<int> DESetupID { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public int BatchID { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<int> BatchCueID { get; set; }
        public Nullable<byte> CutOffStatus { get; set; }
        public Nullable<byte> BatchMode { get; set; }
        public Nullable<byte> SystemType { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<byte> PrintLabels { get; set; }
        public Nullable<int> BatchTypeCode { get; set; }
        public Nullable<short> BatchTypeSubCode { get; set; }
        public string BatchTypeText { get; set; }
        public Nullable<byte> ConsolidationStatus { get; set; }
        public Nullable<byte> CARStatus { get; set; }
        public Nullable<byte> KFIStatus { get; set; }
        public Nullable<byte> FAXStatus { get; set; }
        public Nullable<byte> FloatAssignmentStatus { get; set; }
        public Nullable<byte> ScanStatus { get; set; }
        public Nullable<byte> DEStatus { get; set; }
        public Nullable<int> ExtractSequenceNumber { get; set; }
        public Nullable<int> ImageExtractSequenceNumber { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<int> CheckCount { get; set; }
        public Nullable<decimal> CheckAmount { get; set; }
        public Nullable<int> StubCount { get; set; }
        public Nullable<decimal> StubAmount { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BillingTC { get; set; }
        public Nullable<int> BillingRT { get; set; }
        public Nullable<int> BillingAccount { get; set; }
        public Nullable<int> BillingSerial { get; set; }
        public Nullable<int> WorkgroupID { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
        public Nullable<byte> MICRVerifyStatus { get; set; }
        public Nullable<short> DEPrinted { get; set; }
        public Nullable<byte> Is2Pass { get; set; }
        public Nullable<byte> UseCar { get; set; }
        public Nullable<int> NoChecksEnclosed { get; set; }
        public Nullable<int> Rejects { get; set; }
        public Nullable<bool> DepositTicketPrinted { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public Nullable<int> TransportID { get; set; }
        public Nullable<int> TrayID { get; set; }
        public Nullable<int> SubTrayID { get; set; }
        public byte UseCustomer { get; set; }
        public string DepositDDA { get; set; }
        public Nullable<System.DateTime> EncodeComplete { get; set; }
        public bool SplitsEnded { get; set; }
        public Nullable<int> SiteCode { get; set; }
        public Nullable<System.DateTime> BitonalImageRemovalDate { get; set; }
        public Nullable<System.DateTime> DataRemovalDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string TransportBatchID { get; set; }
        public Nullable<System.DateTime> GrayScaleImageRemovalDate { get; set; }
        public Nullable<System.DateTime> ColorImageRemovalDate { get; set; }
        public Nullable<System.DateTime> CWDBDataRemovalDate { get; set; }
        public Nullable<System.DateTime> CWDBBitonalImageRemovalDate { get; set; }
        public Nullable<System.DateTime> CWDBGrayScaleImageRemovalDate { get; set; }
        public Nullable<System.DateTime> CWDBColorImageRemovalDate { get; set; }
        public string BatchName { get; set; }
        public Nullable<System.Guid> BatchTypeID { get; set; }
        public byte DecisionStatus { get; set; }
        public bool AllowDecisioning { get; set; }
        public bool RequireDEBeforeTwoPass { get; set; }
        public Nullable<int> OriginalGlobalBatchID { get; set; }
        public string BatchExtractID { get; set; }
        public bool IsImageExchange { get; set; }
        public Nullable<int> CaptureSiteCodeID { get; set; }
        public byte BatchSourceKey { get; set; }
        public int NumOLDDaysRolled { get; set; }
    }
}
