//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecksDataEntry
    {
        public int GlobalCheckID { get; set; }
        public int GlobalBatchID { get; set; }
        public int TransactionID { get; set; }
        public string ACHDetailAccountNumber { get; set; }
        public string ACHBatchCompanyID { get; set; }
        public string ACHBatchCompanyName { get; set; }
        public string ACHBatchEntryClass { get; set; }
        public string ACHBatchCompanyData { get; set; }
        public string ACHBatchEntryDesc { get; set; }
        public string ACHBatchDescriptiveDate { get; set; }
        public Nullable<System.DateTime> ACHBatchEffectiveDate { get; set; }
        public Nullable<System.DateTime> ACHBatchSettlementDate { get; set; }
        public string ACHDetailIndividualID { get; set; }
        public string ACHDetailReceivingCompany { get; set; }
        public string ACHDetailTraceNumber { get; set; }
        public string ACHDetailDiscretionaryData { get; set; }
        public string ACHDetailIndividualName { get; set; }
        public string ACHDetailOFACIndicator1 { get; set; }
        public string ACHDetailOFACIndicator2 { get; set; }
        public string ACHDetailReceivingIndividual { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<short> ReasonCode { get; set; }
        public Nullable<short> CollectionStatus { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> AmountToDate { get; set; }
        public Nullable<System.DateTime> WriteOffDate { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<decimal> PostedAmount { get; set; }
        public Nullable<int> EntityType { get; set; }
        public string EntityID { get; set; }
        public string Collector { get; set; }
        public Nullable<int> DisbursementNumber { get; set; }
        public string Agency { get; set; }
        public Nullable<byte> Is3rdParty { get; set; }
        public Nullable<int> PredepositStatus { get; set; }
        public Nullable<int> PredepositReason { get; set; }
        public Nullable<System.DateTime> PredepositDate { get; set; }
        public Nullable<System.DateTime> PredictedReleaseDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> UnprocessedDate { get; set; }
        public Nullable<System.DateTime> ModifiedStamp { get; set; }
        public string ModifiedBy { get; set; }
    }
}
