//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int GlobalCheckID { get; set; }
        public int GlobalBatchID { get; set; }
        public int TransactionID { get; set; }
        public Nullable<int> TransactionSequence { get; set; }
        public Nullable<int> BatchSequence { get; set; }
        public Nullable<int> CheckSequence { get; set; }
        public Nullable<byte> Status { get; set; }
        public string RawMICR { get; set; }
        public string RT { get; set; }
        public string Serial { get; set; }
        public string Account { get; set; }
        public string TransactionCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> LogonAmount { get; set; }
        public Nullable<decimal> KFIAmount { get; set; }
        public Nullable<decimal> VerifyAmount { get; set; }
        public Nullable<decimal> EncodeAmount { get; set; }
        public Nullable<decimal> CARAmount { get; set; }
        public Nullable<int> PayeeID { get; set; }
        public Nullable<int> Tray { get; set; }
        public Nullable<int> LogicalPocket { get; set; }
        public Nullable<byte> Pocket { get; set; }
        public Nullable<int> KilledMethod { get; set; }
        public string KFIOperator { get; set; }
        public Nullable<int> KFIUnit { get; set; }
        public Nullable<int> KFIStation { get; set; }
        public string KFIVerificationOperator { get; set; }
        public Nullable<int> KFIVerificationUnit { get; set; }
        public Nullable<int> KFIVerificationStation { get; set; }
        public string KFIMCOperator { get; set; }
        public Nullable<int> KFIMCUnit { get; set; }
        public Nullable<int> KFIMCStation { get; set; }
        public Nullable<decimal> FloatAssigned { get; set; }
        public Nullable<byte> PrintPhoto { get; set; }
        public string DEOperator { get; set; }
        public Nullable<int> DEStation { get; set; }
        public Nullable<int> DEUnit { get; set; }
        public string DEVerifyOperator { get; set; }
        public Nullable<int> DEVerifyStation { get; set; }
        public Nullable<int> DEVerifyUnit { get; set; }
        public Nullable<int> DEBillingKeys { get; set; }
        public Nullable<int> DEDataKeys { get; set; }
        public Nullable<int> ItemDataKeys { get; set; }
        public Nullable<int> ItemRawKeys { get; set; }
        public Nullable<int> ItemBillingKeys { get; set; }
        public Nullable<byte> Recapture { get; set; }
        public Nullable<int> MICRRejected { get; set; }
        public Nullable<int> IsForeign { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
        public Nullable<bool> IsGhost { get; set; }
        public string PocketType { get; set; }
        public string RemitterName { get; set; }
        public byte[] Timestamp { get; set; }
        public string ICRTranKey { get; set; }
        public decimal LARAmount { get; set; }
        public Nullable<int> CARConfidence { get; set; }
        public string TraceNumber { get; set; }
        public bool ImagePresentationCleaned { get; set; }
        public bool ImageRecognitionCleaned { get; set; }
        public bool ImageRegistered { get; set; }
        public bool ImageRequiresICR { get; set; }
        public bool ImageRecognized { get; set; }
        public byte IsIRD { get; set; }
        public Nullable<System.Guid> LockboxDecisioningReasonID { get; set; }
        public Nullable<decimal> CARAmount2 { get; set; }
        public Nullable<int> CARConfidence2 { get; set; }
        public bool CARMatch { get; set; }
        public bool CARMatch2 { get; set; }
        public bool IQARequired { get; set; }
        public Nullable<System.Guid> ExtractAuditID { get; set; }
        public byte MICRQuality { get; set; }
        public string OCRRT { get; set; }
        public string OCRAccount { get; set; }
        public string OCRSerial { get; set; }
        public string OCRTransactionCode { get; set; }
        public string OCRRawMICR { get; set; }
        public Nullable<int> OriginalGlobalCheckID { get; set; }
        public Nullable<System.Guid> TemplateSetupID { get; set; }
        public string ECLCashLetterID { get; set; }
        public Nullable<int> ECLBundleID { get; set; }
        public Nullable<int> ECLSequenceID { get; set; }
        public Nullable<int> OCRConfidence { get; set; }
        public int ResolutionDPI { get; set; }
        public bool IsBusinessCheck { get; set; }
        public bool IsDuplicate { get; set; }
        public Nullable<decimal> StubAmount { get; set; }
    }
}
